/* Generated by Together */

package com.novell.ldap.ldif_dsml;

import com.novell.ldap.LDAPMessage;

abstract public interface LDAPReader {

    /**
     * This method reads a request operation from a data stream and
     * returns the operation encapsulated in an LDAPMessage
     */
    //abstract public LDAPMessage readOperation();
}
