/* Generated by Together */

package com.novell.ldap.ldif_dsml;

import java.io.IOException;
import java.io.InputStream;
import com.novell.ldap.LDAPEntry;
import java.io.OutputStream;

public class LDIFWriter extends LDIF implements LDAPExport {
    public LDIFWriter(OutputStream out) throws IOException  {
        super( );
        super.setVersion( LDIF.LDIF_VERSION_1 );
        return;
    }

    public void writeChange(LDAPOperation change) throws IOException  {
        return;
    }

    public void writeChanges(LDAPOperation[] changes) throws IOException  {
        return;
    }

    public void writeContent(LDAPEntry entry) throws IOException  {
        return;
    }

    public void writeContents(LDAPEntry[] entries) throws IOException  {
        return;
    }

    /**
     * @clientCardinality 1
     * @supplierCardinality 0..*
     */
    private LDAPEntry entry;

    /**
     * @clientCardinality 1
     * @supplierCardinality 0..*
     */
    private LDAPOperation change;
}


