/* **************************************************************************
 * $Id: GetContextIdentityNameResponse.java,v 1.3 2000/08/08 19:43:55 javed Exp $
 *
 * Copyright (C) 1999, 2000 Novell, Inc. All Rights Reserved.
 * 
 * THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
 * TREATIES. USE, MODIFICATION, AND REDISTRIBUTION OF THIS WORK IS SUBJECT
 * TO VERSION 2.0.1 OF THE OPENLDAP PUBLIC LICENSE, A COPY OF WHICH IS
 * AVAILABLE AT HTTP://WWW.OPENLDAP.ORG/LICENSE.HTML OR IN THE FILE "LICENSE"
 * IN THE TOP-LEVEL DIRECTORY OF THE DISTRIBUTION. ANY USE OR EXPLOITATION
 * OF THIS WORK OTHER THAN AS AUTHORIZED IN VERSION 2.0.1 OF THE OPENLDAP
 * PUBLIC LICENSE, OR OTHER PRIOR WRITTEN CONSENT FROM NOVELL, COULD SUBJECT
 * THE PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY. 
 ***************************************************************************/
package com.novell.ldap.ext; 

import org.ietf.ldap.*;
import org.ietf.asn1.*;
import java.io.*;
 
/**
 *      This class is generated by the ExtendedResponseFactory class from
 *  an ExtendedResponse object which has the following OID 
 *  "2.16.840.1.113719.1.27.100.32".
 *
 */
public class GetContextIdentityNameResponse implements ParsedExtendedResponse {
   
   // Identity returned by the server
   private String identity;
   
   /**
    *
    * The constructor parses the responseValue which has the following ASN<br><br>
    *  responseValue ::=<br>
    *  &nbsp;&nbsp;&nbsp;&nbsp;     identity    OCTET STRING
    *
    */   
   public GetContextIdentityNameResponse (LDAPExtendedResponse r) 
        	throws IOException {
        
        // parse the contents of the reply
        byte [] returnedValue = r.getValue();
        if (returnedValue == null)
            throw new IOException("No returned value");
        
        // Create a decoder object
        BERDecoder decoder = new BERDecoder();
        if (decoder == null)
            throw new IOException("Decoding error");
           
        // The only parameter returned should be an octet string
        ASN1OctetString asn1_identity = (ASN1OctetString)decoder.decode(returnedValue);        
        if (asn1_identity == null)
            throw new IOException("Decoding error");
        
        // Convert to normal string object
        identity = new String(asn1_identity.getContent());
        if (identity == null)
            throw new IOException("Decoding error");
   }
   
   /** 
    * @param String value specifying the identity returned by the server
    */
   public String getIdentity() {
        return identity;
   }
    
}
