/* **************************************************************************
 * $OpenLDAP$
 *
 * Copyright (C) 1999 - 2002 Novell, Inc. All Rights Reserved.
 *
 * THIS WORK IS SUBJECT TO U.S. AND INTERNATIONAL COPYRIGHT LAWS AND
 * TREATIES. USE, MODIFICATION, AND REDISTRIBUTION OF THIS WORK IS SUBJECT
 * TO VERSION 2.0.1 OF THE OPENLDAP PUBLIC LICENSE, A COPY OF WHICH IS
 * AVAILABLE AT HTTP://WWW.OPENLDAP.ORG/LICENSE.HTML OR IN THE FILE "LICENSE"
 * IN THE TOP-LEVEL DIRECTORY OF THE DISTRIBUTION. ANY USE OR EXPLOITATION
 * OF THIS WORK OTHER THAN AS AUTHORIZED IN VERSION 2.0.1 OF THE OPENLDAP
 * PUBLIC LICENSE, OR OTHER PRIOR WRITTEN CONSENT FROM NOVELL, COULD SUBJECT
 * THE PERPETRATOR TO CRIMINAL AND CIVIL LIABILITY.
 ******************************************************************************/

package com.novell.ldap;

import java.io.IOException;
import java.net.MalformedURLException;
import java.util.Vector;

import com.novell.ldap.asn1.*;
import com.novell.ldap.rfc2251.*;
import com.novell.ldap.client.*;

/**
 *  A message received from an LDAPServer
 *  in response to an asynchronous request.
 *
 *  <p>Sample Code: <a href="http://developer.novell.com/ndk/doc/samplecode/jldap_sample/asynchronous/Searchas.java.html">Searchas.java</p>
 *
 * @see LDAPConnection#search
 */

 /*
  * Note: Exceptions generated by the reader thread are returned
  * to the application as an exception in an LDAPResponse.  Thus
  * if <code>exception</code> has a value, it is not a server response,
  * but instad an exception returned to the application from the API.
  */
public class LDAPResponse extends LDAPMessage
{
    private LocalException exception = null;
    private ReferralInfo activeReferral;

    /**
     * Creates an LDAPResponse using an LDAPException.
     * Used to wake up the user following an abandon.
     * Note: The abandon doesn't have to be user initiated
     * but may be the result of error conditions.
     * <br>
     * Referral information is available if this connection created solely
     * to follow a referral.
     *
     *  @param ex  The exception
     * <br><br>
     *  @param refeerralList  The list of referrals from the server
     * <br><br>
     *  @param activeReferral  The referral actually used to create the
     *                             connection
     */
    public LDAPResponse( LocalException ex,
                         ReferralInfo activeReferral)
    {
        exception = ex;
        this.activeReferral = activeReferral;
        if( Debug.LDAP_DEBUG) {
            Debug.trace( Debug.messages,
                "new LDAPResponse: referral " + (this.activeReferral != null) +
                "\n\texception:" +  ex.toString());
        }

        return;
    }

    /**
     * Creates an LDAPMessage when receiving an asynchronous response from a
     * server.
     *
     *  @param message  The RfcLDAPMessage from a server.
     */
    /*package*/
    LDAPResponse( RfcLDAPMessage message)
    {
        super(message);
        return;
    }

    /**
     * Returns any error message in the response.
     *
     * @return Any error message in the response.
     */
    public String getErrorMessage()
    {
        if( exception != null) {
            return exception.getLDAPErrorMessage();
        }
        return ((RfcResponse)message.getProtocolOp()).getErrorMessage().getString();
    }

    /**
     * Returns the partially matched DN field from the server response,
     * if the response contains one.
     *
     * @return The partially matched DN field, if the response contains one.
     *
     */
    public String getMatchedDN()
    {
        if( exception != null) {
            return exception.getMatchedDN();
        }
        return ((RfcResponse)message.getProtocolOp()).getMatchedDN().getString();
    }

    /**
     * Returns all referrals in a server response, if the response contains any.
     *
     * @return All the referrals in the server response.
     */
    public String[] getReferrals()
    {
        String[] referrals = null;
        RfcReferral ref = ((RfcResponse)message.getProtocolOp()).getReferral();

        if(ref == null) {
            referrals = new String[0];
        } else {
            // convert RFC 2251 Referral to String[]
            int size = ref.size();
            referrals = new String[size];
            for(int i=0; i<size; i++) {
                String aRef = new String(((ASN1OctetString)ref.get(i)).getContent());
                try {
                    // get the referral URL
                    LDAPUrl urlRef = new LDAPUrl( aRef);
                    if( urlRef.getDN() == null) {
                        RfcLDAPMessage origMsg =
                            super.getASN1Object().getRequestingMessage().getASN1Object();
                        String dn;
                        if( (dn = origMsg.getRequestDN()) != null) {
                            urlRef.setDN( dn);
                            aRef = urlRef.toString();
                        }
                    }
                } catch( MalformedURLException mex) {
                    ;
                } finally {
                    referrals[i] = aRef;
                }        
            }
        }
        return referrals;
   }

    /**
     * Returns the result code in a server response.
     *
     * <p> For a list of result codes, see the LDAPException class. </p>
     *
     * @return The result code.
     */
    public int getResultCode()
    {
        if( exception != null) {
            return exception.getLDAPResultCode();
        }
        return ((RfcResponse)message.getProtocolOp()).getResultCode().getInt();
    }

    /**
     * Checks the resultCode and throws the appropriate exception.
     *
     *  @exception LDAPException A general exception which includes an error
     *  message and an LDAP error code.
     */
    /* package */
    void chkResultCode() throws LDAPException
    {
        if( exception != null) {
            throw exception;
        } else {
            if( Debug.LDAP_DEBUG) {
                Debug.trace( Debug.messages, "LDAPResponse: message(" +
                    getMessageID() + ") result code " + getResultCode());
            }
            LDAPException ex = getResultException();
            if( ex != null) {
                throw ex;
            }
            return;
        }
    }

    /**
     * Checks the resultCode and generates the appropriate exception or
     * null if success.
     */
    /* package */
    LDAPException getResultException()
    {
        LDAPException ex = null;
        switch(getResultCode()) {
        case LDAPException.SUCCESS:
        case LDAPException.COMPARE_TRUE:
        case LDAPException.COMPARE_FALSE:
            break;
        case LDAPException.REFERRAL:
            // only get here if automatic referral handling is not enabled.
            String[] refs = getReferrals();
            if( Debug.LDAP_DEBUG ) {
                Debug.trace( Debug.messages,
                            "LDAPResponse: Generating RfcReferral Exception");
                for( int i = 0; i < refs.length; i++) {
                    Debug.trace( Debug.messages, "LDAPResponse: \t" + refs[i]);
                }
            }
            ex = new LDAPReferralException(
                    "Automatic referral following not enabled",
                    LDAPException.REFERRAL, getErrorMessage());
            ((LDAPReferralException)ex).setReferrals( refs);
            break;
        default: // Everything else
            ex = new LDAPException(
                LDAPException.errorCodeToString( getResultCode()),
                getResultCode(), getErrorMessage(), getMatchedDN());
            break;
        }
        return ex;
    }

    /* Methods from LDAPMessage */

    /**
     * Returns any controls in the message.
     *
     * @see com.novell.ldap.LDAPMessage#getControls()
     */
    public LDAPControl[] getControls() {
        if( exception != null) {
            return null;
        }
        return super.getControls();
    }
    /**
     * Returns the message ID.
     *
     * @see com.novell.ldap.LDAPMessage#getMessageID()
     */
    public int getMessageID() {
        if( exception != null) {
            return exception.getMessageID();
       }
       return super.getMessageID();
    }

    /**
     * Returns the LDAP operation type of the message.
     *
     * @return The operation type of the message.
     *
     * @see com.novell.ldap.LDAPMessage#getType()
     */
    public int getType()
     {
        if( exception != null) {
           return exception.getReplyType();
        }
        return super.getType();
    }

    /**
     * Indicates if this response is an embedded exception response
     *
     * @return true if contains an embedded LDAPexception
     */
     /*package*/
     boolean hasException()
     {
        return (exception != null);
     }

    /**
     * Returns an embedded exception response
     *
     * @return an embedded exception if any
     */
     /*package*/
     LDAPException getException()
     {
        return exception;
     }

    /**
     * Indicates the referral instance being followed if the
     * connection created to follow referrals.
     *
     * @return the referral being followed
     */
     /*package*/
     ReferralInfo getActiveReferral()
     {
        return activeReferral;
     }
}
