/* Generated by Together */

package com.novell.ldap.message;

import com.novell.ldap.*;
import com.novell.ldap.asn1.*;
import com.novell.ldap.rfc2251.*;

/*
 *       BindRequest ::= [APPLICATION 0] SEQUENCE {
 *               version                 INTEGER (1 .. 127),
 *               name                    LDAPDN,
 *               authentication          AuthenticationChoice }
 */
public class LDAPBindRequest extends LDAPMessage
{
    private String dn;
    
    /**
     */
    public LDAPBindRequest( int version,
                            String dn,
                            byte[] passwd,
                            LDAPConstraints cons)
        throws LDAPException
    {
        super( LDAPMessage.BIND_REQUEST,
               new RfcBindRequest(
                    new ASN1Integer(version),
                    new RfcLDAPDN(dn),
                    new RfcAuthenticationChoice(
                         new ASN1Tagged(
                             new ASN1Identifier(ASN1Identifier.CONTEXT,false,0),
                             new ASN1OctetString(passwd),
                             false))), // implicit tagging
               (cons != null) ? cons.getControls() : null);

        this.dn = dn;
        return;
    }
}
