/* Generated by Together */

package com.novell.ldap.message;

import com.novell.ldap.LDAPConstraints;
import com.novell.ldap.LDAPMessage;
import com.novell.ldap.LDAPExtendedOperation;
import com.novell.ldap.asn1.ASN1OctetString;
import com.novell.ldap.client.Debug;
import com.novell.ldap.rfc2251.RfcExtendedRequest;
import com.novell.ldap.rfc2251.RfcLDAPOID;

/* 
 *       ExtendedRequest ::= [APPLICATION 23] SEQUENCE {
 *               requestName      [0] LDAPOID,
 *               requestValue     [1] OCTET STRING OPTIONAL }
 */
public class LDAPExtendedRequest extends LDAPMessage
{    
	public LDAPExtendedRequest(LDAPExtendedOperation op, LDAPConstraints cons)
    {
        super( LDAPMessage.EXTENDED_REQUEST,
               new RfcExtendedRequest(
                   new RfcLDAPOID(op.getID()),
                   (op.getValue() != null) ?
                       new ASN1OctetString(op.getValue()) :
                       null),
               null);
        return;
    }    

    public Object getRequestInfo()
    {
        return null;
    }
}
