/* Generated by Together */

package com.novell.ldap.message;

import com.novell.ldap.*;
import com.novell.ldap.asn1.*;
import com.novell.ldap.rfc2251.*;

/* 
 *       CompareRequest ::= [APPLICATION 14] SEQUENCE {
 *               entry           LDAPDN,
 *               ava             AttributeValueAssertion }
 */
public class LDAPCompareRequest extends LDAPMessage
{
    private String dn;
    
    /**
     */
    public LDAPCompareRequest( String dn,
                               String name,
                               byte[] value,
                               LDAPConstraints cons)
        throws LDAPException
    {
        super( LDAPMessage.COMPARE_REQUEST,
               new RfcCompareRequest(
                   new RfcLDAPDN(dn),
                   new RfcAttributeValueAssertion(
                   new RfcAttributeDescription(name),
                   new RfcAssertionValue(value))),
               (cons != null) ? cons.getControls() : null);

        this.dn = dn;
        return;
    }
}
