/* Generated by Together */

package com.novell.ldap.message;

import com.novell.ldap.*;
import com.novell.ldap.asn1.*;
import com.novell.ldap.client.Debug;
import com.novell.ldap.rfc2251.*;

import java.util.Enumeration;

/**
 * Modification Request.
 *
 *<pre>
 *       ModifyRequest ::= [APPLICATION 6] SEQUENCE {
 *               object          LDAPDN,
 *               modification    SEQUENCE OF SEQUENCE {
 *                       operation       ENUMERATED {
 *                                               add     (0),
 *                                               delete  (1),
 *                                               replace (2) },
 *                       modification    AttributeTypeAndValues } }
 *</pre>
 */
public class LDAPModifyRequest extends LDAPMessage
{
    private String dn;
    
    /**
     */
    public LDAPModifyRequest( String dn,
                              LDAPModification[] mods,
                              LDAPConstraints cons)
        throws LDAPException
    {

        super( LDAPMessage.MODIFY_REQUEST,
               new RfcModifyRequest(
                   new RfcLDAPDN(dn),
                   getModifications(mods)),
               (cons != null) ? cons.getControls() : null);

        this.dn = dn;
        return;
    }
        
    final static
    private ASN1SequenceOf getModifications( LDAPModification[] mods)
    {
        // Convert Java-API LDAPModification[] to RFC2251 SEQUENCE OF SEQUENCE
        ASN1SequenceOf rfcMods = new ASN1SequenceOf(mods.length);
        for(int i=0; i<mods.length; i++) {
            LDAPModification mod = mods[i];
            LDAPAttribute attr = mod.getAttribute();

            // place modification attribute values in ASN1SetOf
            ASN1SetOf vals = new ASN1SetOf(attr.size());
            if( attr.size() > 0) {
                Enumeration attrEnum = attr.getByteValues();
                while(attrEnum.hasMoreElements()) {
                    vals.add(new RfcAttributeValue((byte[])attrEnum.nextElement()));
                }
            }

            // create SEQUENCE containing mod operation and attr type and vals
            ASN1Sequence rfcMod = new ASN1Sequence(2);
            rfcMod.add(new ASN1Enumerated(mod.getOp()));
            rfcMod.add(new RfcAttributeTypeAndValues(
                new RfcAttributeDescription(attr.getName()), vals));

            // place SEQUENCE into SEQUENCE OF
            rfcMods.add(rfcMod);
        }
        return rfcMods;    
    }
}
