/* Generated by Together */

package com.novell.ldap.message;

import com.novell.ldap.*;
import com.novell.ldap.asn1.*;
import com.novell.ldap.client.Debug;
import com.novell.ldap.rfc2251.*;

import java.util.Enumeration;

/*
 *       ModifyDNRequest ::= [APPLICATION 12] SEQUENCE {
 *               entry           LDAPDN,
 *               newrdn          RelativeLDAPDN,
 *               deleteoldrdn    BOOLEAN,
 *               newSuperior     [0] LDAPDN OPTIONAL }
 */
public class LDAPModifyDNRequest extends LDAPMessage
{
    private String dn;
    
    /**
     */
    public LDAPModifyDNRequest( String dn,
                                String newRdn,
                                String newParentdn,
                                boolean deleteOldRdn,
                                LDAPConstraints cons)
        throws LDAPException
    {

        super( LDAPMessage.MODIFY_RDN_REQUEST,
               new RfcModifyDNRequest(
                   new RfcLDAPDN(dn),
                   new RfcRelativeLDAPDN(newRdn),
                   new ASN1Boolean(deleteOldRdn),
                   (newParentdn != null) ?
                       new RfcLDAPDN(newParentdn) : null),
               (cons != null) ? cons.getControls() : null);

        this.dn = dn;
        return;
    }
}
