/* Generated by Together */

package com.novell.ldap.message;

import com.novell.ldap.*;
import com.novell.ldap.rfc2251.*;

/* 
 *       AbandonRequest ::= [APPLICATION 16] MessageID
 */
public class LDAPAbandonRequest extends LDAPMessage
{
    /**
     */
    public LDAPAbandonRequest( int id,
                               LDAPConstraints cons)
        throws LDAPException
    {
        super( LDAPMessage.ABANDON_REQUEST,
               new RfcAbandonRequest( id),
                   (cons != null) ? cons.getControls() : null);
        return;
    }
}
